### ISSUE TITLE
ConnectionTimeoutError: Connection timeout

### ISSUE THREAD

**Issue by vitaliy-shahanyants** [jack3898/discord-youtube-bot-2#11]
I get this error in the Docker logs 
```
> discord-youtube-bot-2@1.0.0 bot

> ts-node src/index.ts -p tsconfig.builds.json


/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163

            socket.setTimeout(__classPrivateFieldGet(this, _RedisSocket_options, "f").connectTimeout, () => socket.destroy(new errors_1.ConnectionTimeoutError()));

                                                                                                                           ^

ConnectionTimeoutError: Connection timeout

    at Socket.<anonymous> (/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163:124)

    at Object.onceWrapper (node:events:639:28)

    at Socket.emit (node:events:520:28)

    at Socket.emit (node:domain:475:12)

    at Socket._onTimeout (node:net:501:8)

    at listOnTimeout (node:internal/timers:559:17)

    at processTimers (node:internal/timers:502:7)

/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163

            socket.setTimeout(__classPrivateFieldGet(this, _RedisSocket_options, "f").connectTimeout, () => socket.destroy(new errors_1.ConnectionTimeoutError()));

                                                                                                                           ^

ConnectionTimeoutError: Connection timeout

    at Socket.<anonymous> (/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163:124)

    at Object.onceWrapper (node:events:639:28)

    at Socket.emit (node:events:520:28)

    at Socket.emit (node:domain:475:12)

    at Socket._onTimeout (node:net:501:8)

    at listOnTimeout (node:internal/timers:559:17)

    at processTimers (node:internal/timers:502:7)

/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163

            socket.setTimeout(__classPrivateFieldGet(this, _RedisSocket_options, "f").connectTimeout, () => socket.destroy(new errors_1.ConnectionTimeoutError()));

                                                                                                                           ^

ConnectionTimeoutError: Connection timeout

    at Socket.<anonymous> (/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163:124)

    at Object.onceWrapper (node:events:639:28)

    at Socket.emit (node:events:520:28)

    at Socket.emit (node:domain:475:12)

    at Socket._onTimeout (node:net:501:8)

    at listOnTimeout (node:internal/timers:559:17)

    at processTimers (node:internal/timers:502:7)

/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163

            socket.setTimeout(__classPrivateFieldGet(this, _RedisSocket_options, "f").connectTimeout, () => socket.destroy(new errors_1.ConnectionTimeoutError()));

                                                                                                                           ^

ConnectionTimeoutError: Connection timeout

    at Socket.<anonymous> (/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163:124)

    at Object.onceWrapper (node:events:639:28)

    at Socket.emit (node:events:520:28)

    at Socket.emit (node:domain:475:12)

    at Socket._onTimeout (node:net:501:8)

    at listOnTimeout (node:internal/timers:559:17)

    at processTimers (node:internal/timers:502:7)

/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163

            socket.setTimeout(__classPrivateFieldGet(this, _RedisSocket_options, "f").connectTimeout, () => socket.destroy(new errors_1.ConnectionTimeoutError()));

                                                                                                                           ^

ConnectionTimeoutError: Connection timeout

    at Socket.<anonymous> (/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163:124)

    at Object.onceWrapper (node:events:639:28)

    at Socket.emit (node:events:520:28)

    at Socket.emit (node:domain:475:12)

    at Socket._onTimeout (node:net:501:8)

    at listOnTimeout (node:internal/timers:559:17)

    at processTimers (node:internal/timers:502:7)

/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163

            socket.setTimeout(__classPrivateFieldGet(this, _RedisSocket_options, "f").connectTimeout, () => socket.destroy(new errors_1.ConnectionTimeoutError()));

                                                                                                                           ^

ConnectionTimeoutError: Connection timeout

    at Socket.<anonymous> (/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163:124)

    at Object.onceWrapper (node:events:639:28)

    at Socket.emit (node:events:520:28)

    at Socket.emit (node:domain:475:12)

    at Socket._onTimeout (node:net:501:8)

    at listOnTimeout (node:internal/timers:559:17)

    at processTimers (node:internal/timers:502:7)

/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163

            socket.setTimeout(__classPrivateFieldGet(this, _RedisSocket_options, "f").connectTimeout, () => socket.destroy(new errors_1.ConnectionTimeoutError()));

                                                                                                                           ^

ConnectionTimeoutError: Connection timeout

    at Socket.<anonymous> (/home/node/node_modules/@node-redis/client/dist/lib/client/socket.js:163:124)

    at Object.onceWrapper (node:events:639:28)

    at Socket.emit (node:events:520:28)

    at Socket.emit (node:domain:475:12)

    at Socket._onTimeout (node:net:501:8)

    at listOnTimeout (node:internal/timers:559:17)

    at processTimers (node:internal/timers:502:7)

Environment: production

Redis host: redis

Bot logged in as ThotMusic!

Started refreshing application slash commands.

19 unique commands have been found on the file system.
```

**Comment by jack3898** [comment]
Hi @vitaliy-shahanyants!

Can you give me some details on what you did to reach this error?
Is this a new bot, or is it something that has suddenly started happening?

Many thanks!

Jack

**Comment by vitaliy-shahanyants** [comment]
We can close this, total users error.

Thank you for response
