### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by melchoir55** [jack3898/discord-youtube-bot-2#21]
Full Error:

```
bot      | SyntaxError: Invalid or unexpected token
bot      |     at new Script (node:vm:100:7)
bot      |     at Object.exports.decipherFormats (/home/node/node_modules/ytdl-core/lib/sig.js:116:51)
bot      |     at runMicrotasks (<anonymous>)
bot      |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
bot      |     at async Promise.all (index 0)
bot      |     at async exports.getInfo (/home/node/node_modules/ytdl-core/lib/info.js:401:17)
```

I'm fairly certain my google api key is valid and working. I tried a bad key and got a different error. 

So, if the key is fine, why would this be happening?

**Comment by melchoir55** [comment]
This happens when ytdl-core is out of date.
